#! /usr/bin/env python
#
#    Dimensionality Reduction Tools
#    Copyright (C) 2010 Ilja Sidoroff
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    dr-error: Calculate error measures for datasets
#
#
import sys

import numpy

import dimred.trustcont as trustcont

if len(sys.argv) < 4:
    print "Usage: dr-error method original reduced"
    sys.exit(1)

orig = numpy.genfromtxt(sys.argv[2])
reduced = numpy.genfromtxt(sys.argv[3])

if orig.shape[0] != reduced.shape[0]:
    print "Data files have different number of rows"
    sys.exit(1)
    
method = sys.argv[1]

if method == "trust":
    trust = trustcont.trustworthiness(orig, reduced, range(1, orig.shape[0]-1))
    for v in trust:
        print v

    sys.exit(0)
elif method == "cont":
    cont = trustcont.continuity(orig, reduced, range(1, orig.shape[0]-1))
    for v in cont:
        print v

    sys.exit(0)
else:
    print "Supported methods: trust (trustworthiness), cont (continuity)"
    sys.exit(1)
