#! /usr/bin/env python
#
#    Dimensionality Reduction Tools
#    Copyright (C) 2010 Ilja Sidoroff
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    dr-plot: Visualize results
#
#

import sys

import numpy
import matplotlib.pyplot as plt

if len(sys.argv) < 3:
    print "Usage: dr-plot data [labels]"
    sys.exit(1)

orig = numpy.genfromtxt(sys.argv[1])
labels = None

if len(sys.argv) > 2:
    f = open(sys.argv[2])
    labels = [ int(x) for x in f.read().split() ]

fig = plt.figure()
ax = plt.subplot(111)

plt.plot(orig[:,0], orig[:,1])
plt.show()
